name: tflite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '3.19.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tflite_camera_plugin:
    path: plugins/tflite_camera_plugin
  path_provider: ^2.1.2
  auto_route: ^7.8.4
  freezed_annotation: ^2.4.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  native_device_orientation: ^2.0.3
  json_annotation: ^4.8.1
  photo_view: ^0.14.0
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  arb_utils: 0.1.0+1
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/