import 'dart:ui';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:tflite/common/detections/bounding_box.dart';

part 'detected_object.freezed.dart';

@Freezed(fromJson: false, toJson: false)
class DetectedObject with _$DetectedObject {
  const factory DetectedObject({
    required int categoryIndex,
    required double categoryScore,
    required BoundingBox boundingBox,
  }) = _DetectedObject;

  factory DetectedObject.fromPluginData(Map<String, dynamic> json) {
    return DetectedObject(
      categoryIndex: json['categoryIndex'] as int,
      categoryScore: json['categoryScore'] as double,
      boundingBox: BoundingBox(
        Offset(json['left'], json['top']),
        Offset(json['right'], json['bottom']),
      ),
    );
  }
}

// This was the training set of titles the net was trained on.
const cocoLabels = <String>[
  "person",
  "bicycle",
  "car",
  "motorcycle",
  "airplane",
  "bus",
  "train",
  "truck",
  "boat",
  "traffic light",
  "fire hydrant",
  "street sign",
  "stop sign",
  "parking meter",
  "bench",
  "bird",
  "cat",
  "dog",
  "horse",
  "sheep",
  "cow",
  "elephant",
  "bear",
  "zebra",
  "giraffe",
  "hat",
  "backpack",
  "umbrella",
  "shoe",
  "eye glasses",
  "handbag",
  "tie",
  "suitcase",
  "frisbee",
  "skis",
  "snowboard",
  "sports ball",
  "kite",
  "baseball bat",
  "baseball glove",
  "skateboard",
  "surfboard",
  "tennis racket",
  "bottle",
  "plate",
  "wine glass",
  "cup",
  "fork",
  "knife",
  "spoon",
  "bowl",
  "banana",
  "apple",
  "sandwich",
  "orange",
  "broccoli",
  "carrot",
  "hot dog",
  "pizza",
  "donut",
  "cake",
  "chair",
  "couch",
  "potted plant",
  "bed",
  "mirror",
  "dining table",
  "window",
  "desk",
  "toilet",
  "door",
  "tv",
  "laptop",
  "mouse",
  "remote",
  "keyboard",
  "cell phone",
  "microwave",
  "oven",
  "toaster",
  "sink",
  "refrigerator",
  "blender",
  "book",
  "clock",
  "vase",
  "scissors",
  "teddy bear",
  "hair drier",
  "toothbrush",
  "hair brush",
];
